version: '2'

services:
    docker_project:
      container_name: my_server
      build:
        context: .
        dockerfile: Dockerfile
      ports:
        - 8000:5000
      volumes:
        - .docker/storage.json:/home/docker_project/storage.json
      networks:
        - network

    redis_server:
      image: redis
      ports:
      - 6379:6379
      networks:
        - network

networks:
  network: {}

# docker-compose up --build
